# Generated by Django 4.2.11 on 2026-05-25 11:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSource",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("SAP", "SAP ERP Export"),
                            ("ELECTRICITY", "Utility Electricity Portal"),
                            ("TRAVEL", "Corporate Travel Platform"),
                        ],
                        help_text="Type of data source. Determines parsing strategy.",
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='e.g., "SAP Production Instance", "Grid Building C"',
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Notes about data quality, frequency, contacts",
                    ),
                ),
                (
                    "last_sync",
                    models.DateTimeField(
                        blank=True,
                        help_text="When data was last successfully ingested",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="If False, uploads from this source are rejected",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company that owns this record",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.company",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "source_type"],
                        name="core_dataso_company_16e80c_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="core_dataso_is_acti_aef0dd_idx"
                    ),
                ],
                "unique_together": {("company", "source_type", "name")},
            },
        ),
    ]
