# Generated by Django 4.2.11 on 2026-05-25 11:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RawRecord",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        help_text="Original uploaded row as key-value pairs"
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        help_text="Name of uploaded CSV file", max_length=255
                    ),
                ),
                (
                    "row_number",
                    models.PositiveIntegerField(
                        help_text="Which row in the CSV (1-indexed)"
                    ),
                ),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("UPLOADED", "Uploaded, awaiting processing"),
                            ("PROCESSING", "Currently being processed"),
                            ("SUCCESS", "Successfully normalized"),
                            ("FAILED", "Failed during processing"),
                        ],
                        db_index=True,
                        default="UPLOADED",
                        help_text="Current stage in processing pipeline",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="If FAILED, describes what went wrong"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company that owns this record",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.company",
                    ),
                ),
                (
                    "data_source",
                    models.ForeignKey(
                        help_text="Which source this record came from",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_records",
                        to="core.datasource",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "processing_status"],
                        name="ingestion_r_company_847e53_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="ingestion_r_created_44d7b3_idx"
                    ),
                    models.Index(
                        fields=["data_source", "processing_status"],
                        name="ingestion_r_data_so_050cd6_idx",
                    ),
                ],
                "unique_together": {("data_source", "file_name", "row_number")},
            },
        ),
    ]
