# Generated by Django 4.2.11 on 2026-05-25 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ingestion", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NormalizedEmissionRecord",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("SAP", "SAP ERP"),
                            ("ELECTRICITY", "Utility Electricity"),
                            ("TRAVEL", "Corporate Travel"),
                        ],
                        help_text="Which source type this came from",
                        max_length=20,
                    ),
                ),
                (
                    "scope",
                    models.IntegerField(
                        choices=[
                            (1, "Scope 1 - Direct Emissions"),
                            (2, "Scope 2 - Indirect Emissions (Energy)"),
                            (3, "Scope 3 - Other Indirect Emissions"),
                        ],
                        help_text="GHG Protocol scope classification",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("fuel_gasoline", "Fuel - Gasoline"),
                            ("fuel_diesel", "Fuel - Diesel"),
                            ("fuel_natural_gas", "Fuel - Natural Gas"),
                            ("fuel_lpg", "Fuel - LPG"),
                            ("fuel_other", "Fuel - Other"),
                            ("procurement_goods", "Procurement - Goods"),
                            ("procurement_services", "Procurement - Services"),
                            ("electricity_grid", "Electricity - Grid"),
                            ("steam_heating", "Steam/Heating"),
                            ("steam_cooling", "Steam/Cooling"),
                            ("travel_flight", "Travel - Flight"),
                            ("travel_hotel", "Travel - Hotel"),
                            ("travel_ground", "Travel - Ground Transport"),
                            ("commuting", "Employee Commuting"),
                            ("waste", "Waste"),
                        ],
                        help_text="Detailed category for emission factor lookup",
                        max_length=50,
                    ),
                ),
                (
                    "facility_code",
                    models.CharField(
                        help_text="SAP plant code, meter ID, or facility identifier",
                        max_length=50,
                    ),
                ),
                (
                    "facility_name",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable facility name",
                        max_length=255,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Amount in original units",
                        max_digits=18,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        help_text="Original unit (L, kWh, km, etc.)", max_length=20
                    ),
                ),
                (
                    "quantity_standardized",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Amount in kg CO2e (standardized)",
                        max_digits=18,
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True, help_text="When this emission occurred"
                    ),
                ),
                (
                    "vendor",
                    models.CharField(
                        blank=True,
                        help_text="Supplier/vendor if applicable",
                        max_length=255,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional context or data quality notes"
                    ),
                ),
                (
                    "is_flagged",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this record requires analyst review",
                    ),
                ),
                (
                    "flag_reason",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dict of reasons why flagged: {reason: detail}",
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False,
                        help_text="Once approved and locked, cannot be edited",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company that owns this record",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.company",
                    ),
                ),
                (
                    "raw_record",
                    models.OneToOneField(
                        help_text="Original uploaded data",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="normalized_record",
                        to="ingestion.rawrecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATED", "Record Created"),
                            ("APPROVED", "Record Approved"),
                            ("REJECTED", "Record Rejected"),
                            ("EDITED", "Record Modified"),
                            ("LOCKED", "Record Locked"),
                        ],
                        help_text="What action was taken",
                        max_length=20,
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dict of changes: {field: {old_value, new_value}}",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of request", null=True
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        help_text="Who performed the action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company that owns this record",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.company",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        help_text="Which record was changed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="normalization.normalizedemissionrecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewQueue",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reason_flagged",
                    models.CharField(
                        help_text="Summary of why flagged", max_length=255
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low - Minor issue"),
                            ("MEDIUM", "Medium - Data quality concern"),
                            ("HIGH", "High - Requires clarification"),
                        ],
                        default="MEDIUM",
                        help_text="How urgent is this review",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Awaiting Review"),
                            ("APPROVED", "Approved by Analyst"),
                            ("REJECTED", "Rejected - Will Not Use"),
                        ],
                        db_index=True,
                        default="PENDING",
                        help_text="Current approval status",
                        max_length=20,
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, help_text="When was it reviewed", null=True
                    ),
                ),
                (
                    "reviewer_notes",
                    models.TextField(
                        blank=True, help_text="Analyst comments and reasoning"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company that owns this record",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.company",
                    ),
                ),
                (
                    "normalized_record",
                    models.OneToOneField(
                        help_text="Record requiring review",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_queue_item",
                        to="normalization.normalizedemissionrecord",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who approved/rejected this",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "status"],
                        name="normalizati_company_ba5966_idx",
                    ),
                    models.Index(
                        fields=["company", "severity"],
                        name="normalizati_company_b8b95a_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="normalizati_status_da2bf2_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PlantLookup",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sap_plant_code",
                    models.CharField(
                        help_text="Code from SAP (e.g., PL001, FA_BERLIN)",
                        max_length=50,
                    ),
                ),
                (
                    "facility_name",
                    models.CharField(
                        help_text="Human-readable facility name", max_length=255
                    ),
                ),
                (
                    "facility_address",
                    models.CharField(
                        blank=True, help_text="Street address", max_length=500
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(
                        blank=True, help_text="Geographic latitude", null=True
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        blank=True, help_text="Geographic longitude", null=True
                    ),
                ),
                (
                    "scope_1_applicable",
                    models.BooleanField(
                        default=True,
                        help_text="Does this facility have Scope 1 emissions?",
                    ),
                ),
                (
                    "scope_2_applicable",
                    models.BooleanField(
                        default=True,
                        help_text="Does this facility have Scope 2 emissions?",
                    ),
                ),
                (
                    "scope_3_applicable",
                    models.BooleanField(
                        default=True,
                        help_text="Does this facility have Scope 3 emissions?",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company that owns this record",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.company",
                    ),
                ),
            ],
            options={
                "ordering": ["facility_name"],
                "indexes": [
                    models.Index(
                        fields=["company", "sap_plant_code"],
                        name="normalizati_company_31db58_idx",
                    ),
                    models.Index(
                        fields=["facility_name"], name="normalizati_facilit_54b267_idx"
                    ),
                ],
                "unique_together": {("company", "sap_plant_code")},
            },
        ),
        migrations.AddIndex(
            model_name="normalizedemissionrecord",
            index=models.Index(
                fields=["company", "is_flagged"], name="normalizati_company_0e2d02_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="normalizedemissionrecord",
            index=models.Index(
                fields=["company", "date"], name="normalizati_company_7e16ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="normalizedemissionrecord",
            index=models.Index(
                fields=["company", "scope"], name="normalizati_company_675c3e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="normalizedemissionrecord",
            index=models.Index(
                fields=["company", "facility_code"],
                name="normalizati_company_1a4f9c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="normalizedemissionrecord",
            index=models.Index(
                fields=["is_locked"], name="normalizati_is_lock_e8b294_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["record", "-created_at"], name="normalizati_record__8c1b7b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["company", "action"], name="normalizati_company_bcdb5f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["actor"], name="normalizati_actor_i_ab0202_idx"),
        ),
    ]
