# Generated by Django 4.2.11 on 2026-05-25 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("normalization", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewqueue",
            name="normalized_record",
            field=models.OneToOneField(
                blank=True,
                help_text="Record requiring review",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_queue_item",
                to="normalization.normalizedemissionrecord",
            ),
        ),
    ]
